[package]
name = "frontend"
version = "0.1.0"
edition = "2024"

[dependencies]
gloo = "0.11"
js-sys = "0.3"
wasm-bindgen = "0.2"
yew = { git = "https://github.com/yewstack/yew/", features = ["csr"] }
material-yew = { git = "https://github.com/MagewireDev/material-yew"}

